AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fred_data_api_sam

  Sample SAM Template for fred_data_api_sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 2048
    Runtime: python3.7

Parameters:

    ISDEPLOYED:
        Description: 'Required. The Database username'
        Type: 'String'

    DBPWD:
        Description: 'Required. The Database username'
        Type: 'String'

    DBURL:
        Description: 'Required. The Database username'
        Type: 'String'

    DBUSER:
        Description: 'Required. The Database username'
        Type: 'String'

    APITOKEN:
        Description: 'Required. The Database username'
        Type: 'String'

Resources:
  FredMetadataFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: fred_metadata/
      Handler: app.lambda_handler
      Runtime: python3.7
      Environment:
        Variables:
          IS_DEPLOYED: !Ref ISDEPLOYED
          econ_data_password: !Ref DBPWD
          econ_data_url: !Ref DBURL
          econ_data_user: !Ref DBUSER
          fred_api_token: !Ref APITOKEN
      Events:
        FredMetadata:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /FredMetadata
            Method: get
        ScheduledFredMetadata:
          Type: Schedule
          Properties:
            Schedule: cron(0/10 * ? * MON-FRI *)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FredMetadataApi:
    Description: "API Gateway endpoint URL for Prod stage for Fred Metadata function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  FredMetadataFunction:
    Description: "Fred Metadata download Lambda Function ARN"
    Value: !GetAtt FredMetadataFunction.Arn
  FredMetadataFunctionIamRole:
    Description: "Implicit IAM Role created for Fred Metadata download function"
    Value: !GetAtt FredMetadataFunctionRole.Arn
